// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxQl_Y4ZiRonB59tUkQNtzlffgTJ2MzsA',
    appId: '1:194231740608:web:94936f52a7dcb0e14be525',
    messagingSenderId: '194231740608',
    projectId: 'bucket-list-a47f9',
    authDomain: 'bucket-list-a47f9.firebaseapp.com',
    storageBucket: 'bucket-list-a47f9.firebasestorage.app',
    measurementId: 'G-PNC5PW5R5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiwaJ3co-jugWo0scToa5U9YfAli79QwU',
    appId: '1:194231740608:android:d8b3caadaaba2ec94be525',
    messagingSenderId: '194231740608',
    projectId: 'bucket-list-a47f9',
    storageBucket: 'bucket-list-a47f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCccef0jB30_78gAKJD9nOkIb-dMK4lbhk',
    appId: '1:194231740608:ios:e2e9a277125373444be525',
    messagingSenderId: '194231740608',
    projectId: 'bucket-list-a47f9',
    storageBucket: 'bucket-list-a47f9.firebasestorage.app',
    iosBundleId: 'com.example.bucketList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCccef0jB30_78gAKJD9nOkIb-dMK4lbhk',
    appId: '1:194231740608:ios:e2e9a277125373444be525',
    messagingSenderId: '194231740608',
    projectId: 'bucket-list-a47f9',
    storageBucket: 'bucket-list-a47f9.firebasestorage.app',
    iosBundleId: 'com.example.bucketList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxQl_Y4ZiRonB59tUkQNtzlffgTJ2MzsA',
    appId: '1:194231740608:web:de416bb78d2808074be525',
    messagingSenderId: '194231740608',
    projectId: 'bucket-list-a47f9',
    authDomain: 'bucket-list-a47f9.firebaseapp.com',
    storageBucket: 'bucket-list-a47f9.firebasestorage.app',
    measurementId: 'G-G63RR96KCN',
  );
}
